#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,20.2,7
#
clock.xem3: package/cfg/clock.xem3.mak

clean::
	-$(RM) package/cfg/clock.xem3.mak
